[project]
name = "pdf-renamer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pillow>=12.0.0",
    "pyinstaller>=6.17.0",
    "pymupdf>=1.24.0",
    "pywebview[qt]>=6.1",
    "requests>=2.31.0",
]
